# Generated by Django 3.2.2 on 2021-05-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('description', models.TextField()),
                ('nbstock', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('taille', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('site', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbarticle', models.IntegerField()),
                ('etat', models.CharField(default='non traitée', max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionstock.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionstock.client')),
            ],
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('site', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('login', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.CharField(max_length=100)),
                ('prix_tva', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionstock.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionstock.commande')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionstock.categorie'),
        ),
    ]
