# Generated by Django 3.2.2 on 2021-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
