# Generated by Django 3.2.2 on 2021-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionstock', '0002_auto_20210520_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='img',
            field=models.ImageField(upload_to='../media/images'),
        ),
    ]
