# Generated by Django 3.2.2 on 2021-05-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionstock', '0003_alter_utilisateur_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
