# Generated by Django 3.2.2 on 2021-05-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionstock', '0005_alter_utilisateur_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='img',
        ),
    ]
