# Generated by Django 3.2.2 on 2021-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionstock', '0006_remove_utilisateur_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
